baseURL: https://atopchumfa2022.netlify.app/
title: Arman Topchu's website for Data Analytics for Finance
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: Favorite quotes
      name: Favorite quotes
      url: /fav-quotes/
      weight: 2
    - identifier: Favorite movies
      name: Favorite movies
      url: /fav-movies/
      weight: 3
    - identifier: Favorite series
      name: Favorite series
      url: /fav-series/
      weight: 4
    - identifier: Favorite R Professor
      name: Favorite R Professor
      url: /not-u/
      weight: 5

params:
contact:
    address:
      - city: London
        country: UK
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: atopchu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 0 770 000 0000
        title: Phone

  author: Arman Topchu
  description: Website for Data Analytics for Finance
  menu_item_separator: ' - '
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/EVEBITDA
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/arman.prive
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/armantopchu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/armantopchu
  
  goldmark:
    renderer:
      unsafe: true
