baseURL: https://atopchumfa2022.netlify.app/
title: Arman Topchu's website for Data Analytics for Finance (MFA2022)
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: Favorite quotes
      name: Favorite quotes
      url: /fav-quotes/
      weight: 2
    - identifier: Favorite movies
      name: Favorite movies
      url: /fav-movies/
      weight: 3
    - identifier: Favorite series
      name: Favorite series
      url: /fav-series/
      weight: 4
    - identifier: Favorite R Professor
      name: Favorite R Professor
      url: /not-u/
      weight: 5
params:
  author: Arman Topchu
  description: Website for Data Analytics for Finance (MFA2022)
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio

markup:
  goldmark:
    renderer:
      unsafe: true
