baseURL: https://atopchumfa2022.netlify.app/
title: Arman Topchu's website for Data Analytics for Finance (MFA2022)
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Arman Topchu
  description: Website for Data Analytics for Finance (MFA2022)
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
