baseURL = "https://atopchumfa2022.netlify.app/"
title = "Arman Topchu's website for Data Analytics for Finance"
themesDir = "../.."
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Favorite quotes"
    name = "Favorite quotes"
    url = "/fav-quotes/"
    weight = 2
  [[menu.main]]
    identifier = "Favorite movies"
    name = "Favorite movies"
    url = "/fav-movies/"
    weight = 3
  [[menu.main]]
    identifier = "Favorite series"
    name = "Favorite series"
    url = "/fav-series/"
    weight = 4
  [[menu.main]]
    identifier = "Favorite R Professor"
    name = "Favorite R Professor"
    url = "/not-u/"
    weight = 5

[params]
  author = "Arman Topchu"
  description = "Websire for Data Analytics"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "twitter"
    name = "Hugo's twitter"
    url = "https://twitter.com/gohugoio"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
